create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null check (role in ('student', 'teacher', 'admin')) default 'student',
  created_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  description text not null default '',
  base_type text not null check (base_type in ('intro', 'binary', 'octal', 'decimal', 'hexadecimal')),
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  title text not null,
  problem text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  completed boolean not null default false,
  score numeric(5, 2),
  updated_at timestamptz not null default now(),
  unique (lesson_id, user_id)
);

alter table public.profiles enable row level security;
alter table public.lessons enable row level security;
alter table public.exercises enable row level security;
alter table public.lesson_progress enable row level security;

create policy "Users can read their profile" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "Users can create their profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "Users can update their profile" on public.profiles for update to authenticated using (auth.uid() = id);
create policy "Anyone authenticated can read published lessons" on public.lessons for select to authenticated using (published = true or exists (select 1 from public.profiles where id = auth.uid() and role in ('teacher', 'admin')));
create policy "Teachers and admins can manage lessons" on public.lessons for all to authenticated using (exists (select 1 from public.profiles where id = auth.uid() and role in ('teacher', 'admin'))) with check (exists (select 1 from public.profiles where id = auth.uid() and role in ('teacher', 'admin')));
create policy "Authenticated users can read exercises" on public.exercises for select to authenticated using (true);
create policy "Teachers and admins can create exercises" on public.exercises for insert to authenticated with check (exists (select 1 from public.profiles where id = auth.uid() and role in ('teacher', 'admin')) and created_by = auth.uid());
create policy "Users can read their progress" on public.lesson_progress for select to authenticated using (user_id = auth.uid());
create policy "Users can write their progress" on public.lesson_progress for insert to authenticated with check (user_id = auth.uid());
create policy "Users can update their progress" on public.lesson_progress for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

insert into public.lessons (title, slug, description, base_type)
values
  ('บทนำ', 'intro', 'ทำความรู้จักกับระบบเลขฐาน', 'intro'),
  ('ฐานสอง', 'binary', 'เรียนรู้เลขฐานสองและการคำนวณ', 'binary'),
  ('ฐานแปด', 'octal', 'เรียนรู้เลขฐานแปดและการคำนวณ', 'octal'),
  ('ฐานสิบ', 'decimal', 'เรียนรู้เลขฐานสิบและการคำนวณ', 'decimal'),
  ('ฐานสิบหก', 'hexadecimal', 'เรียนรู้เลขฐานสิบหกและการคำนวณ', 'hexadecimal')
on conflict (slug) do nothing;
